function figu=fig2(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stem x
%  Y1:  stem y

%  Auto-generated by MATLAB on 27-Sep-2019 15:58:36

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on');
box(axes1,'on');
hold(axes1,'on');

% Create stem
stem(X1,Y1);

% Create xlabel
xlabel('n');

% Create ylabel
ylabel('|f[n]|');

% Create title
title('	|f[n]| vs n');

