function gra= grafica(X1,Y1)


%CREATEFIGURE(X1, Y1)
%  X1:  stem x
%  Y1:  stem y

%  Auto-generated by MATLAB on 26-Sep-2019 20:24:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create stem
stem(X1,Y1,'Color',[0 0.498039215803146 0]);

% Create xlabel
xlabel('n	');

% Create ylabel
ylabel('x[n]');

% Create title
title('x[n]=n(a^n)');

% Create textbox
annotation(figure1,'textbox',...
    [0.77377486910995 0.832781456953642 0.0702041884816752 0.0645695364238411],...
    'String',{'a=0.9'},...
    'FitBoxToText','off');
